### PR TITLE
pico_gl: Add instanced rendering and vertex step function

### PR DESCRIPTION
**Pull request by Tuhkis**
I made instanced rendering its own draw calls since the API already had different draw calls for different types of drawing (like `pgl_draw_array(...)` & `pgl_draw_indexed_array(...)`)

The vertex step functions could theoretically support things like step per every other instance or only step through position data per instance, but I thought that a bit redundant.

I fixed a few spelling errors too :P

### CODE REVIEW

**Comment by empyreanx** [comment]
In the library I'm working with there is a distinction between the vertex step function and the vertex step (which I assume is the same as the divisor in OpenGL). I think that both the vertex step function and and the vertex step (divisor) should be passed as arguments when setting up the attributes. 

For brevity I would suggest renaming `pgl_vertex_set_function_t` to `pgl_vertex_step_t`. In the docs (and perhaps in the examples) I would make it clear that `0` is synonymous with `PGL_VERTEX_STEP_PER_VERTEX`. 

Lastly I would just like to say that pico_gl was not designed with instancing in mind. You can perform some instancing, but I imagine you'll run up against the limits of uniform sizes fairly quickly. That's not to say you shouldn't try.

**Comment by empyreanx** [comment]
It appears that the contributor has lost  interest in this PR, so I'm closing it for now.

**Comment by Tuhkis** [comment]
Yes. I kind of forgot about this as I was on vacation and couldn't really figure out, how to make the api feel "nice."

Better to close. Sorry for wasting your time.

**Comment by empyreanx** [comment]
No apology necessary! Thank you for your interest in my project.

**Pull request closed without merging**
